// Package Declaration
package calculator

// Imports Begin
import std.io.*
// Imports End

class Arithmetics {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public func div(a: Int64, b: Int64): Int64 {
		throw Exception('TODO')
	}
	public func mul(a: Int64, b: Int64): Int64 {
		throw Exception('TODO')
	}
	public func sub(a: Int64, b: Int64): Int64 {
		throw Exception('TODO')
	}
	public func add(a: Int64, b: Int64): Int64 {
		throw Exception('TODO')
	}
	// Class Methods End

}

