// Package Declaration
package Calculator

// Imports Begin
import std.collection.*
import std.io.*
// Imports End

class HistoryLogger {
	// Class Fields Begin
	internal let history: Array<String> = []
	// Class Fields End

	// Class Methods Begin
	public func clear():  {
		// TODO
	}
	public func getHistory(): Array<String> {
		// TODO
	}
	public func log(operation: String, result: Int64):  {
		// TODO
	}
	// Class Methods End

}

