// Package Declaration
package com.example.helloworld

// Imports Begin
import com.example.helloworld.HelloWorld
import std.io.*
// Imports End

class HelloWorldTest {
	// Class Fields Begin
	internal let outputStream:  = ?
	internal let originalOut:  = ?
	// Class Fields End

	// Class Methods Begin
	internal func testHelloWithSpecialCharacters(): Unit {
		// TODO
	}
	internal func testHelloWithEmptyName(): Unit {
		// TODO
	}
	internal func testHelloWithName(): Unit {
		// TODO
	}
	internal func testHelloWithoutName(): Unit {
		// TODO
	}
	internal func setUp(): Unit {
		// TODO
	}
	// Class Methods End

}

