// Package Declaration
package Calculator.test

// Imports Begin
import calculator.Arithmetics
import std.io.*
// Imports End

class ArithmeticsTest {
	// Class Fields Begin
	internal let arithmetics: Arithmetics = ?
	// Class Fields End

	// Class Methods Begin
	internal func testDivByZero():  {
		// TODO
	}
	internal func testDiv():  {
		// TODO
	}
	internal func testMul():  {
		// TODO
	}
	internal func testSub():  {
		// TODO
	}
	internal func testAdd():  {
		// TODO
	}
	// Class Methods End

}

