// Package Declaration
package Calculator.test

// Imports Begin
import calculator.HistoryLogger
import calculator.Calculator
import std.io.*
// Imports End

class CalculatorTest {
	// Class Fields Begin
	internal var calculator: Calculator = ?
	// Class Fields End

	// Class Methods Begin
	internal func testHistoryLogging():  {
		// TODO
	}
	internal func testInvalidInput():  {
		// TODO
	}
	internal func testPerformDiv():  {
		// TODO
	}
	internal func testPerformMul():  {
		// TODO
	}
	internal func testPerformSub():  {
		// TODO
	}
	internal func testPerformAdd():  {
		// TODO
	}
	internal func setUp():  {
		// TODO
	}
	// Class Methods End

}

