// Package Declaration
package Calculator.test

// Imports Begin
import calculator.HistoryLogger
import std.io.*
// Imports End

class HistoryLoggerTest {
	// Class Fields Begin
	internal var logger: HistoryLogger = ?
	// Class Fields End

	// Class Methods Begin
	internal func testGetHistoryReturnsCopy():  {
		// TODO
	}
	internal func testClear():  {
		// TODO
	}
	internal func testMultipleLogs():  {
		// TODO
	}
	internal func testLog():  {
		// TODO
	}
	internal func setUp():  {
		// TODO
	}
	// Class Methods End

}

