// Package Declaration
package calculator

// Imports Begin
import std.io.*
// Imports End

class Calculator {
	// Class Fields Begin
	internal let math: Arithmetics = Arithmetics()
	// Class Fields End

	// Class Methods Begin
	public func performDiv(x: Int64, y: Int64): Int64 {
		throw Exception('TODO')
	}
	public func performMul(x: Int64, y: Int64): Int64 {
		throw Exception('TODO')
	}
	public func performSub(x: Int64, y: Int64): Int64 {
		throw Exception('TODO')
	}
	public func performAdd(x: Int64, y: Int64): Int64 {
		throw Exception('TODO')
	}
	// Class Methods End

}

