// Package Declaration
package com.example.helloworld

// Imports Begin
import std.collection.*
import std.io.*
// Imports End

class HelloWorld {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public static func main(args: Array<String>): Unit {
		// TODO
	}
	public static func hello(name: String): Unit {
		// TODO
	}
	public static func hello(): Unit {
		// TODO
	}
	// Class Methods End

}

